theme: jekyll-theme-minimal
title: Average cost per square meter in Poland [PLN]
description: The map shows the average price per square meter of residential premises sold under market transactions in 2020. The data comes from the real estate market database of the Central Statistical Office of Poland. 
logo: logo.jpg
